#!/bin/bash

bold="\e[1m"
bold_green="${bold}\e[32m"
normal="\e[0m"

echo -e "[${bold_green}Initializing docker database${normal}]"

export PGPASSWORD=postgres
psql -h localhost -U postgres \
    < "$(dirname "$0")/sql/init/01-create-users.sql"
	
psql -h localhost -U postgres \
    < "$(dirname "$0")/sql/init/02-create-databases.sql"
